Booster can be initialized even if Kryo is not available
Fixes a bug in the code, when Kryo is not available KryoBooster cannot
be loaded because of NoClassDefFoundError instead of ClassNotFoundException